name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # v4 वर अपडेट केले
      - name: Set up Node.js
        uses: actions/setup-node@v4 # v4 वर अपडेट केले
        with:
          node-version: 18
      - name: Set up JDK 17         # नवीन अँड्रॉइडसाठी JDK 17 आवश्यक आहे
        uses: actions/setup-java@v4 # v4 वर अपडेट केले
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Install Cordova
        run: npm install -g cordova
      - name: Build APK
        run: |
          cordova platform add android
          cordova build android --no-telemetry
      - name: Upload APK
        uses: actions/upload-artifact@v4 # इथे v4 केल्यामुळे एरर निघून जाईल
        with:
          name: app-release-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
